# Generated by Django 5.0.6 on 2024-05-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='cat_image')),
            ],
        ),
        migrations.CreateModel(
            name='Airways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('ava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avakomp', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Davlatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='dav_image')),
                ('dav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davlatlar', to='app.category')),
            ],
        ),
    ]
